in_data: '../Wiesen.gpkg'
out_data: '../Wiesen_test.gpkg' #put same path as in_data and overwrite to true to update existing layers
overwrite: true
max_join_distance: 1

count_name: Number
class_count_name: ClassNumber
parent_name: ParentID
wiesen_name: Wiese
class_name: Class

layers:
  fruchtdraht:
    layer_name: Fruchtdraht #the name of the layer in the geopackage
    type: base_layer

  ger체st:
    layer_name: Geruest
    type: join_layer

  b채ume:
    layer_name: Baeume
    type: join_layer

naturamon:
  in_data: '../Wiesen_test.gpkg'
  b채ume_layer: Baeume
  ger체st_layer: Geruest
  out_data: ../Naturamon/